services:
  - type: web
    name: krish-mart
    runtime: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: krish-mart-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: krish-mart-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: krish-mart-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: krish-mart-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: krish-mart-db
          property: password

databases:
  - name: krish-mart-db
    plan: free
    region: oregon
